# Generated by Django 2.0.6 on 2018-06-14 23:49

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='qrCode',
            field=models.CharField(default=services.models.Reuniao.generate_token, editable=False, max_length=20),
        ),
    ]
