# Generated by Django 2.0.6 on 2018-06-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_reuniao_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparece',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Grupo'),
        ),
        migrations.AlterField(
            model_name='comparece',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Reuniao'),
        ),
        migrations.AlterField(
            model_name='coordena',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nomeGrupo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Organizacao'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Grupo'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='registro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='representa',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Organizacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomeUsuario',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
