# Generated by Django 2.0.6 on 2018-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180616_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='registro',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
