# Generated by Django 2.0.6 on 2018-06-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180618_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='registro',
            field=models.CharField(max_length=20),
        ),
    ]
