# Generated by Django 2.0.6 on 2018-06-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180618_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participa',
            name='registro',
        ),
    ]
