# Generated by Django 2.0.6 on 2018-06-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_participa_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='participa',
            name='registro',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
