# Generated by Django 2.0.6 on 2018-06-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_participa_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='representa',
            name='visitante',
        ),
        migrations.AddField(
            model_name='representa',
            name='pessoa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Visitante',
        ),
    ]
