# Generated by Django 2.0.6 on 2018-06-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='MDA'),
        ),
    ]
