# Generated by Django 2.0.6 on 2018-06-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20180618_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
    ]
