# Generated by Django 2.0.6 on 2018-06-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_usuario_foto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reuniao',
            unique_together={('data', 'horaInicio', 'data')},
        ),
    ]
