# Generated by Django 2.0.6 on 2018-06-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20180618_1948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reuniao',
            unique_together={('data', 'horaInicio', 'grupo')},
        ),
    ]
