# Generated by Django 2.0.6 on 2018-06-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20180618_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparece',
            name='grupo',
        ),
    ]
