# Generated by Django 2.0.6 on 2018-06-18 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_remove_participa_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparece',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='comparece',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.Usuario'),
            preserve_default=False,
        ),
    ]
